# Generated by Django 4.0.5 on 2022-12-30 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.ImageField(upload_to='courseimg')),
                ('course_name', models.CharField(max_length=100)),
                ('course_des', models.TextField()),
                ('course_duration', models.PositiveIntegerField()),
                ('course_price', models.PositiveIntegerField()),
            ],
        ),
    ]
